= opentransport-mbedtls

This is a project to port mbedtls to the Retro68 toolchain for m68k and PPC Macs running an Open Transport networking stack.  My main interest is getting enough of mbedtls working to use libssh2.

see https://tls.mbed.org/kb/how-to/how-do-i-port-mbed-tls-to-a-new-environment-OS

TODO:

* [*] minimal config.h
* [*] build
* [*] implement network functions (basic, blocking only, TCP only)
* [*] implement entropy source (more or less)
* [ ] implement clock functions (not required for functionality)
* [*] implement filesystem functions (mostly done? seems like retro68 did everything)
* [ ] implement timing functions (not required for functionality)

== entropy
The classic Mac OS doesn't provide a real RNG.  This code uses the clock tick count and the mouse cursor position.  If you have any suggests for more entropy, I'd love to hear them.

== notes
build via:

mkdir build && cd build

cmake .. -DCMAKE_TOOLCHAIN_FILE=/path/to/Retro68-build/toolchain/powerpc-apple-macos/cmake/retroppc.toolchain.cmake -DUNSAFE_BUILD=ON -DENABLE_TESTING=Off -DENABLE_PROGRAMS=Off -DCMAKE_BUILD_TYPE=Release

make && make install

